name: Install Build Tools
description: Installs cmake, ninja and clang
author: T-im4i-k

runs:
  using: "composite"
  steps:
    - name: Check runner OS
      shell: bash
      run: |
        if [ "$RUNNER_OS" != "Linux" ]; then
          printf "Error: OS %s is not supported.\n" "$RUNNER_OS"
          exit 1
        fi

    - name: Update apt-get
      shell: bash
      run: |
        printf "Updating apt-get...\n"
        if ! sudo apt-get update &>/dev/null; then
          printf "Error: apt-get update failed.\n"
          exit 1
        fi

    - name: Install cmake, ninja and clang
      shell: bash
      run: |
        bash "${{github.action_path}}/install_build_tools.sh"