name: Test Action

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test-on-good-project:
    runs-on: [ ubuntu-latest ]

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Install build tools
        shell: bash
        run: |
          sudo apt-get update && \
          sudo apt-get install -y cmake ninja-build clang-18

      - name: Configure good project
        shell: bash
        run: |
          cd "test/good_project/"
          cmake -B build -S . -DCMAKE_CXX_COMPILER=clang++ -G Ninja

      - name: Run clang-tidy-check action on good project
        uses: ./
        with:
          compile-commands-path: "./test/good_project/build/compile_commands.json"


  test-on-poor-project:
    runs-on: [ ubuntu-latest ]

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Install build tools
        shell: bash
        run: |
          sudo apt-get update && \
          sudo apt-get install -y cmake ninja-build clang-18

      - name: Configure poor project
        shell: bash
        run: |
          cd "test/poor_project/"
          cmake -B build -S . -DCMAKE_CXX_COMPILER=clang++ -G Ninja

      - name: Run clang-tidy-check action on poor project
        id: clang-tidy-check-poor-project
        uses: ./
        continue-on-error: true
        with:
          compile-commands-path: "./test/poor_project/build/compile_commands.json"

      - name: Verify last step fail
        shell: bash
        run: |
          if [ "${{steps.clang-tidy-check-poor-project.outcome}}" != "failure" ]; then
              printf "Error: expected clang-tidy-check-poor-project setp to fail"
              exit 1
          fi